"""patch 010 1a extend products

Revision ID: 7b3fe58d1bf4
Revises: 3e6543c7a255
Create Date: 2026-07-23 10:16:49.342897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3fe58d1bf4'
down_revision: Union[str, Sequence[str], None] = '3e6543c7a255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('short_name', sa.String(length=100), nullable=True))
    op.add_column('cart_items', sa.Column('hsn_code', sa.String(length=30), nullable=True))
    op.add_column('cart_items', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('cart_items', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('cart_items', sa.Column('meta_keywords', sa.Text(), nullable=True))
    op.add_column('cart_items', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cart_items', sa.Column('is_new_arrival', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cart_items', sa.Column('is_best_seller', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cart_items', sa.Column('min_stock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('cart_items', sa.Column('max_stock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('cart_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('short_name', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('hsn_code', sa.String(length=30), nullable=True))
    op.add_column('products', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('meta_keywords', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_new_arrival', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('is_best_seller', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('min_stock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('max_stock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'max_stock')
    op.drop_column('products', 'min_stock')
    op.drop_column('products', 'is_best_seller')
    op.drop_column('products', 'is_new_arrival')
    op.drop_column('products', 'meta_keywords')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    op.drop_column('products', 'hsn_code')
    op.drop_column('products', 'short_name')
    op.drop_column('cart_items', 'deleted_at')
    op.drop_column('cart_items', 'max_stock')
    op.drop_column('cart_items', 'min_stock')
    op.drop_column('cart_items', 'is_best_seller')
    op.drop_column('cart_items', 'is_new_arrival')
    op.drop_column('cart_items', 'is_featured')
    op.drop_column('cart_items', 'meta_keywords')
    op.drop_column('cart_items', 'meta_description')
    op.drop_column('cart_items', 'meta_title')
    op.drop_column('cart_items', 'hsn_code')
    op.drop_column('cart_items', 'short_name')
    # ### end Alembic commands ###
